# Site settings
title: Meme and Meaning
email: admin@memeandmeaning.com
url: https://memeandmeaning.com
author: Steven Horkey
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
timezone: America/Phoenix

# Footer settings
footer: Meme and Meaning

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: youtube
    url: https://www.youtube.com/channel/UC84CWjf9QtBm9lQBGEiNVFg
  - title: instagram
    url: https://instagram.com/memeandmeaning
  - title: facebook
    url: https://facebook.com/memeandmeaning
  # - title: email
  #   url: http://bitbucket.org/jekyll
    
# Build settings
markdown: kramdown
permalink: pretty