# Site settings
title: Meme and Meaning
email: admin@memeandmeaning.com
url: https://memeandmeaning.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
timezone: America/Phoenix

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#F09E55'

# Footer settings
footer: Meme and Meaning

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: youtube
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: instagram
    url: https://instagram.com/memeandmeaning
  - title: facebook
    url: https://facebook.com/memeandmeaning
  # - title: email
  #   url: http://bitbucket.org/jekyll
    
# Build settings
markdown: kramdown
permalink: pretty

# Slider
slider:
  text_color: white
  shadow_color: black
  slides: 
    - image: /img/introimgbig.jpg
      slide_html:
    - image: /img/tree_jungle.jpg
      slide_html: "<h3>La Passione 1/2</h3>Shirley, do you own a Ferrari?"
    - image: /img/downloads-bg.jpg
      slide_html: "<h3>La Passione 2/2</h3>Yes, my life is your dream."
    - image: /img/justin-shuler.jpg
      slide_html:


