# Site settings
title: Meme and Meaning
email: admin@memeandmeaning.com
url: http://memeandmeaning.com
author: Steven Horkey
description: "Musings on all things related to life and what it takes to live it well. Free content and resources on science, psychology, philosophy, and consciousness."
timezone: America/Phoenix

# Footer settings
footer: Meme and Meaning

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: youtube
    url: https://www.youtube.com/channel/UC84CWjf9QtBm9lQBGEiNVFg
  - title: instagram
    url: https://instagram.com/memeandmeaning
  - title: facebook
    url: https://facebook.com/memeandmeaning
  # - title: email
  #   url: http://bitbucket.org/jekyll
    
# Build settings
markdown: kramdown
permalink: /:title/

steven-img: '/Users/steven/Desktop/mm-site/img/steven1.jpg'

# plugins: 
#   - jekyll-sitemap