# Site settings
title: Meme and Meaning
email: admin@memeandmeaning.com
url: https://memeandmeaning.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#F09E55'

# Footer settings
footer: Meme and Meaning

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/memeandmeaning
  - title: facebook
    url: https://facebook.com/memeandmeaning
  - title: youtube
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: email
    url: http://bitbucket.org/jekyll
    
# Build settings
markdown: kramdown
permalink: pretty
